import React from 'react';

function About( props ) {
    return (
        <div className="inner-container">
            <h1>About</h1>
            <p>VOCAL RANGE
                In its broadest sense, the term vocal range refers to the full spectrum of notes that a singer's voice is able to produce, starting from the bottommost note and reaching to the uppermost note. In other words, range refers to the distance between the highest and lowest pitches that a singer is able to sing. This extreme range of the individual's voice, consisting of all non-utilizable, utterable but nondescript vocal sounds, measured from the lowest grunt to the highest obtainable vocal squeak may also be called 'vocable compass'.

                An untrained singer typically has a more limited range than a well-trained singer, who has learned how to gain access to more notes through correct technique and through regularly exercising and using the vocal instrument for singing tasks. Every instrument has its own unique range capabilities, as well, with some voices being able to develop more extensive ranges than others.

                In opera or solo classical music, often only the parts of the range that are considered musically useful are counted as part of the range. 'Usefulness' with regards to range in classical style singing is defined by consistency of timbre and the ability to 'project' the pitches effectively. For example, since falsetto pitches are not used in most opera, they are not considered part of the vocal range of a male opera singer. Also, if any pitch cannot be properly carried (i.e. heard over an orchestra without amplification), it is not considered part of the range. While a singer may have access to many more notes both above and below his or her 'useful range, those notes are not necessarily counted or used when singing classical song selections. (In the keyboard diagrams of vocal ranges below, only the expected, 'publicly performable' range for each voice type is highlighted.) The range of vocal tones that can be rendered with some degree of musicality may also be referred to as 'singable compass'.

                Put even more simply, a certain section of a singer's range, (likely the middle portion), will make up his or her most comfortable and practical range, whereas other sections of the same singer's range, (the highest and lowest portions), will be available or accessible, but will not necessarily be as strong or as desirable in tone. Thus, a mezzo-soprano might have a two octave 'useful' range for classical repertoire purposes, yet have access to another octave or so above that range and another half octave or so below it.

                In choral music, where many voices are singing in unison, it is somewhat less important for each individual voice to be flawlessly produced or completely audible over the orchestra. Therefore, the range that a certain voice type might be expected to sing in a choir may be a little broader than it would be in opera or in solo performances, (as is suggested in the diagrams indicating the range for each voice type below).

                In contemporary styles of singing, singers typically employ amplification (i.e. microphones, speakers, etc.) when performing, which makes more of their range audible and thus usable.

                To learn about how you can find your vocal range, read the section on range in How To Determine Singing Range and Vocal Fach (Voice Type).

                REGISTERS AND VOCAL REGISTRATION
                The term register can be somewhat confusing, as it encompasses several aspects of the human voice, including a certain vibratory pattern of the vocal folds, a particular range of pitches, and a characteristic type of tone or quality of sound. In other words, a register in the human voice is a particular series of tones that possess the same quality and that are produced in the same vibratory pattern of the vocal folds within a certain range or series of pitches. Vocal registers originate in the laryngeal function (i.e., the larynx, where the vocal folds are located) and occur when the vibratory pattern of the vocal folds changes as pitch rises or falls.

                Singers and singing teachers can aurally identify these changes in voice quality when singing two or more octaves of a musical scale. When transitions from one voice quality to another occur, most singers report some sort of non-specific, kinesthetically sensed, neuromuscular coordination adjusment in the larynx as well as a change in sound or tone. Among experienced or trained singers, the transitions are perceived to be blended and smooth, whereas the transitions among inexperienced singers are more commonly abrupt or awkward (as when a 'register break' occurs).

                Vocal registration refers to the system of vocal registers within the human voice. Research by speech pathologists and vocal pedagogues has revealed that the vocal folds are capable of producing at least four distinct vibratory patterns, which, in turn, create four different registers within the human voice, although not everyone can produce all four of them. Each of these four registers has its own vibratory pattern, its own pitch area (although there is some overlapping), and its own characteristic sound. Most vocal teachers today divide the human voice into three registers; chest (also referred to as natural or modal), middle and head (includes falsetto in males), although many do acknowledge the vocal fry register in their lower voiced male students and the flageolet or whistle register in higher voiced females, as well. However, both of these potential highest and lowest registers are sometimes considered to be extensions of the chest and head registers, rather than unique registers.

                In many contemporary singing methods, a two-register model is advocated. (I explain why this is both inaccurate and counterproductive to vocal training in the Vocal Registration and Contemporary Teaching Methods section of my article entitled 'Belting' Technique.) Since the chest voice and the head voice can be made to overlap considerably, many vocal teachers don't acknowledge the existence of a middle register, but might instead treat the middle section of the voice as a zona di passaggio in which the chest and head tones will become blended or mixed. There may also be some disagreement on what constitutes head voice or how it is defined, and this confusion may explain why some teachers call the lighter tone of the voice that begins at the first passaggio in female students (or any tone that is produced at pitches above the chest register) 'head voice' whereas classical teachers would refer to this register as 'middle' and the register beginning around E5-F#5 (at the secondo passaggio) as the true head register.

                Vocal teachers and singers will often talk about 'bridging the registers' or 'blending the registers', which simply refers to a technique or method of making the transition from one vocal register to the next smooth and seamless, and thus removing all noticeable signs of a register break, which requires an adjustment of breath control and vowel modification (aggiustamento), as well as gradual laryngeal (e.g., muscular) adjustments throughout the scale. More information about blending the registers can be found in my article entitled Good Tone Production For Singing, as well as in Tips For Practicing Singing: A Practical Guide To Vocal Development.

                There is also a great deal of disagreement about the terminology assigned to the vocal registers, primarily because the terms themselves tend to describe where the most resonance is felt in the body as opposed to where the action of the voice is truly originating from (i.e., the larynx). For example, 'head voice' is called such because much of the resonance of the voice is experienced as sympathetic vibrations in the bones of the face and resonating cavities of the head. (The bony structures of the head can be set into sympathetic vibration, but not into actual resonance. Bone is a very good conductor of sympathetic vibration.) Also, most "chest resonance" actually originates in the throat (i.e., the larynx, or 'voice box'), where the vocal folds are located. Since the chest is filled with so many soft organs which do not aid in creating resonance, and because the vocal tract lies above the chest, producing sound after air has already left the chest, many argue that there can be little true resonance created within the chest itself. For this reason, most vocal teachers prefer to use the term 'voice' rather than 'register'. However, some singers do experience a distinct sensation of (sympathetic) vibration in the chest, especially in the sternum or breastbone area, or in the head when singing. These sensations are realistic to the singer and can serve as reliable indicators of resonance balance.

                PASSAGGI (REGISTRATION PIVOTAL POINTS) AND REGISTER BREAKS
                The term 'passaggio', (which is Italian for 'passage'), refers to the place (i.e. the absolute pitch) within a vocal range where the voice 'shifts' or transitions into a different register. In other words, a passaggio marks the end or boundary of one register and the beginning of the next.

                It is generally taught that the human voice has two passaggi - a primo (first) passaggio and a secondo (second) passaggio, connected through a zona di passaggio (passage zone). (In female voices, the zona di passaggio is most likely to be referred to as a separate register, called the middle register or medium voice, which occupies a full octave in range.) In male voices, the primo passaggio marks the pivotal point between the speech-inflection range (the range of pitches in which they habitually speak) and the call range of the speaking voice (the range of pitches in which they would have to call or yell in order to try to speak). Using the call voice through the zona di passaggio - roughly the interval of a fourth - would require greater effort and considerable discomfort. Therefore, most men begin to sing in either mixed or head voice tones throughout their zona di passaggio. For females, who tend to use more inflection and a greater range of pitches during ordinary speaking demands, speech-inflection range continues through the middle register and ends at the secondo passaggio, which marks the beginning of head voice range.

                Similar registration events occur in all voices, male and female. However, they happen at different degrees in the scale. In general, the longer the vocal folds and the larger the larynx, the lower the registration pivotal points (passaggi) in the scale and the lower the voice category. (This also accounts for the pitch differences between male and female speaking and singing voices.) For example, the tenor's primo passaggio, (occurring somewhere between C#4 and E4, depending on the individual's voice), lies roughly a minor or major third above that of the baritone, (occurring around B3 or Bb3), with his secondo passaggio occurring roughly a fourth above his primo passaggio. Most women experience their first registration pivotal point between Eb4 and G4, and their second (upper) passaggio between Eb5 and G5, with the alto's voice switching into the next register a little earlier in the ascending scale than the soprano's voice would. Also, within the same category (e.g., baritones, tenors, altos, sopranos, etc.), heavier voices will experience their primo passaggio slightly lower than lighter voices will (e.g., a dramatic mezzo-soprano might switch into the next register a semitone lower than a lyric mezzo soprano might).

                Additionally, due to the greater diversity of laryngeal size and vocal-tract construction among males, range demarcations among male voice categories are more distinct than those of female voices. The passaggio points of male voices can be plotted over a wider range of notes. In males, a number of specific pitch designations for the passaggi exist within each voice category (e.g., several possible notes for tenor voices, and quite a few for baritones and basses), whereas only a semitone or whole-tone difference exists within female categories.

                If a singer doesn't allow the larynx to progressively make changes (e.g., the vocal folds should ideally change into different vibratory patterns and either elongate or shorten gradually) while ascending and descending in pitch - referred to as 'static laryngeal function' - a register break will occur. Breaks are typically marked by noticeable changes of tone quality and volume. For example, when a female singer moves upward from her chest register into her middle register, her tone may abruptly become thin and weak, or her voice may crack or even cut out completely. Flatting or sharping notes at the passaggi is also quite common amongst untrained singers.

                A major goal of classical voice training is to maintain an even timbre or consistency of tone throughout the passaggi, so that moving through them, or singing within them, is seamless, effortless and undetectable to the listener. This is often referred to as 'blending the registers' or using a 'mixed voice', which I write more about in my article on this site entitled Good Tone Production For Singing, as well as in Tips For Practicing Singing: A Practical Guide To Vocal Development. Bridging the registers, which also requires vowel modification and adjustments of breath management, is essential for creating an evenly balanced, homogonous tone throughout a singer's entire range.

                For a practical way to locate your lower and upper passaggi, please refer to the passaggi section of How To Determine Singing Range and Vocal Fach (Voice Type).

                VOCAL FRY REGISTER
                The vocal fry register, (also known as pulse register and glottal fry/rattle/scrape, amongst other names), is the lowest vocal register that can be produced by a human voice. In contemporary styles of singing, 'vocal fry' may also refer to a voice quality that may be added to any part of the singer's range for vocal effect. Vocal fry is characterized by a rattling, crackling, creaking, croaking, or frying sound quality. It is produced through use of a loose glottal closure that permits air to bubble through slowly. During the vocal fry mode of phonation, the arytenoid cartilages in the larynx compress together in such a fashion that the vocal folds become relatively compact and slack, or 'floppy'. This process forms a large and (usually) irregularly (or non-periodically) vibrating mass within the vocal folds - the vocal folds vibrate far less often per second than in 'normal' voice production, with successive vibrations differing in duration and/or size - that produces the characteristic low popping or rattling sound when air passes through the slackened glottal closure.

                Singers typically use this mode of phonation to obtain pitches at a very low frequency that they may not otherwise be able to access in the chest register, although it can be carried up into the chest register, as well.

                Vocal fry has become enormously popular within many contemporary methods of voice training, and is frequently used very heavily during lessons and in practice routines. It is seldom employed in a prescriptive fashion or as a corrective devise - to, for example, relax hyperfunctioning adductor muscles or to release intrinsic muscular tension. Rather, its use is suggested for all singers as a regular part of their voice training. Those who support the use of vocal fry claim that it is safe and relaxing, like a groggy 'morning voice', especially when the larynx is encouraged to remain lower, the throat 'open', and the vibratory rate is made more regular. These same supporters claim that the belief that fry is potentially damaging to the vocal instrument if used frequently or for long periods of time is merely a myth.

                However, most ENTs and speech language pathologists consider vocal fry to be the result of either dysfunction or poor usage. The physiological production of vocal fry can be potentially damaging to the vocal folds if used frequently or for extended periods of time, particulary if it is brought up into the chest and middle registers and if it is created with a raised larynx and a closed throat. http://www.ohniww.org/katy-perry-voice-vocal-fry/ contains a video of a stroboscopy of both clear and vocal fry production. The squeezing and increased intrinsic muscular effort that are required to produce vocal fry are quite clearly seen, even though the vocal folds themselves are slack and relaxed.

                Therefore, vocal fry as a tone quality or mode of phonation should be limited to the occasional vocal effect (e.g., at the beginning of a phrase, etc.). Although it may be used as an effective tool for teaching and developing certain contemporary techniques and skills, such as growling and screaming, not everyone agrees that it promotes healthy voice production, especially when the glottis is not functioning in an otherwise 'normal' manner, and when the slackness of the vocal folds does not closely mimic or approximate the action, tension and functioning necessary to obtain precision in the onsets of sound, along with a healthy and steady vibratory rate.

                Until more recently, there has been little mention of the vocal fry register in singing pedagogy (and especially in classical circles) for several reasons. First, not everyone can access the pitches that lie below the chest register. (It is more common for lower voiced males - basses - to sing pitches low enough to be considered to be within the actual vocal fry register. A distinction is drawn here between the vocal fry register and the vocal fry effect or quality that is added as a stylistic element for brief parts of notes or words.) Secondly, not all teachers of voice consider this part of a singer's range to be a separate register from chest voice. Many feel as though it is merely a lower extension of the chest register. (This is likely the case in medium and higher voices who cannot access this lowermost register.) Thirdly, vocal fry is not considered by all to be a legitimate, useful or pleasant performance timbre, (although it is often added as a desirable vocal effect at the beginnings of phrases in contemporary styles of singing). Fourthly, it is a potentially unhealthy mode of phonation, as it may cause damage to the vocal folds, especially if used frequently. (As stated above, stroboscopic observation shows heavy squeezing of the arytenoid cartilages.) Fifthly, frequently using this mode of phonation in the chest register can cause a singer to lose some of his or her range, specifically the higher notes within the chest register.

                You can read more about the vocal fry register in Good Tone Production For Singing.

                CHEST REGISTER (MODAL OR NORMAL OR NATURAL VOICE)
                Modal (or normal or natural or chest) register refers to the natural disposition or manner of actions of the vocal folds. The vast majority of speaking is done in this register - men speak entirely within their chest register, while women speak in both their chest and middle registers. (As a result, some teachers might refer to it as occurring at 'speech level', although female speech inflection also occurs above this register.) It lies above the vocal fry or pulse register (achieved typically by basses or contrabasses) and overlaps with the lower part of the head voice register in males and the middle voice in females. It begins and ends in different places within the human voice, depending on voice category or type, although it can be carried upwards, through the primo passaggio, into the middle (women) or head (men) registers. (This practice is widely considered to be potentially injurious to the vocal instrument.) The placement of the chest register within the individual human voice is one of the key determining factors in identifying voice type.

                The timbre of chest voice is warmer and darker ('oscuro') than that of middle and head voice, and it is characterized by darker vowel qualities or mellowness. Chest voice (voce di petto) is often referred to as the heavy (laryngeal) mechanism because more thick vocal mass - more of the vocal folds - is involved in phonation within this lower register. (The vocal folds are thickest and fattest in the chest register.).

                For more information about the natural voice, refer to the Chest Voice section in Good Tone Production for Singing.

                MIDDLE REGISTER AND ZONA DI PASSAGGIO
                In women, the register between chest voice and head voice is called the middle register, or medium voice. For most women the range of pitches between the primo (first) and secondo (second) passaggi is about an octave. The timbre of this register is generally thought to be a mix of both the chest and the head voice qualities, or an in between colour, giving it a very warm, rich tone that isn't quite as oscuro (dark) as that of chest voice but also not quite as chiaro (bright) as that of head voice.

                The zona di passaggio is the term that is used for the middle voice in men that lies between the primo and secondo passaggi. The range of this register is roughly about a major third or a fourth. As in the female middle voice, it is generally viewed as a mixture or a blending of both chest and head voice tones, although many instructors and singers see the benefit of using mainly head voice tones throughout this range in order to facilitate a smoother, less problematic transition into the head register. (Using purely chest voice in this area of the range produces a shouty, 'calling' voice that usually feels strained and requires increased effort.) Ideally, there should be a graduated adjustment or shifting relationships among the muscles involved in pitch change, otherwise known as aggiustamento.

                To learn more about achieving an ideal blended tone in the middle register, read Blending the Registers, Middle Register or Mixed/Blended Voice or The Zona Di Passaggio in Good Tone Production For Singing and Blending (or Bridging) the Registers in Tips For Practicing Singing: A Practical Guide To Vocal Development.

                FALSETTO
                Throughout history, the term falsetto has had various meanings for different groups of users, leading to a great deal of confusion about how to define it. Most commonly in the elite professional male singing voice, falsetto denotes a specific timbre or vocal sound (differentiated from head voice, or voce piena in testa) in the male upper-range that is imitative of upper-range female voice quality, although it is not solely such. The term itself - derived from the Italian word for 'false' - suggests a departure from timbre reality; from true or legitimate vocal timbre.

                The term falsetto sometimes refers to the vocal register occupying the frequency range just above the modal (or chest) register and overlapping with it by approximately one octave. This definition is misleading, however, as falsetto is not a vocal register by definition. Many voice teachers incorrectly use the terms 'falsetto' and 'head voice' interchangeably, inaccurately labeling any pitch produced above a male singer's primo passaggio falsetto. Falsetto then becomes confused with full, legitimate head voice, or assumed to be the same thing.

                Although falsetto is a type of tonal quality that does indeed run 'parallel' to, or alongside, the male head register in terms of range, the two occuring through roughly the same range of pitches, falsetto and head voice do not refer to the same mode of phonation. They are produced by employing different techniques and have different sounds. In both speaking and singing, falsetto is more limited in dynamic variation and tone quality than both head voice and chest voice.

                In falsetto production, the vocalis muscle are inactive and lengthened tremendously by the action of the cricothyroid muscles, which are nearly at their maximum contraction. The mass corresponding to the innermost part of the thyro-arytenoid musscle remains still and motionless. The unique sound of falsetto is produced by the air blowing over the very thin edges of the thyroarytenoids, and the pitch is controlled mostly by a regulation of the breath flow. The very thin edges of the lengthened folds, which do not display any tension in opposition to the stretching action of the thyroarytenoids, are easily blown open by the breath and therefore offer little resistance to the breath flow. (The extreme membrenous edges - the edges furthest from the middle of the gap between the folds - appear to be the only parts vibrating.) Falsetto is relatively weak in overtones and produces no Singer's Formant. Head voice, on the other hand, is richer in overtones and has the potential to produce a substantial Singer's Formant, or 'ring'. In head voice, the thyroarytenoids create a 'tighter' and more substantial edge to the vocal folds, which, in turn, resist the flow of breath, allowing more noticeable pressure below the vocal folds (subglottal breath presuure) to build. The male singer can easily sense this difference in breath pressure between the true head voice and the falsetto, and may feel a sense of muscular relief when he changes from full voice to falsetto timbre.

                The difference between falsetto and head voice is primarily a matter of timbre or specific vocal technique used to achieve the tone that is unique to falsetto. Although it is possible to reinforce falsetto timbre, making it less raspy or breathy in quality through altering relationships among the muscles of the glottal opening/closure system, neither the function nor the resultant tone is identical to that of full head voice. Substituting falsetto for full (head) voice in any male category, or relying upon falsetto for high-lying pitches rather than avoiding the discipline required in order to develop full head voice tones in the upper register is not a good practice, as it suggests an inability to achieve a completely balanced vocal scale.

                Falsetto also refers to a vocal technique that enables the male singer to sing notes beyond the vocal range of the normal (chest, modal or natural) voice. Falsetto is produced when the vocal folds are intentionally allowed to remain slightly separated during phonation. (Vocal fold elongation still takes place in male falsetto, but vocal fold adduction during falsetto remains slacker and incomplete.) The length or size of the oval orifice, or separation between the folds, can vary, but it is known to get bigger in size as the pressure of air pushed out is increased. There are various techniques for producing this tone, and research has revealed that different singers may employ different amounts of vocal fold mass or length, different degrees of glottal closure and more or less reinforcement through breath pressure during falsetto production (e.g., skilled singers maintain a smaller opening between the folds than untrained singers do, with the vocal folds coming in closer contact with each other during each vibration cycle and the arytenoid cartilages held in firmer apposition, creating a clearer, less raspy falsetto tone). In some singers, a phenomenon known as damping appears, with the amount of glottal opening becoming less and less as the pitch rises, until only a tiny slit appears on the highest pitches.

                It is not standard practice to say that a female singer is using a falsetto voice, because when a woman's vocal folds are not fully approximated, her tone merely sounds breathy. Unlike the male instrument, the female instrument is incapable of producing a timbre in upper range that is radically different from its full (head) voice qualities. Furthermore, when energy and support is reduced in the female voice, (as it is in the male voice during falsetto), her tone is likely to sound distorted.

                For more details on falsetto tone production, refer to the Falsetto section in Good Tone Production For Singing.

                HEAD VOICE
                The head register lies above the middle register or zona di passaggio. The term 'head voice' is generally used to describe the feeling that the resonance (sympathetic resonance) of singing is occurring primarily in the head. It has a characteristic 'ringing' tone and modified acoustics (modified vowel sounds).

                Head voice (voce di testa) is sometimes called the 'lighter mechanism' of the voice because mass reduces as the vocal folds elongate. As a result, most singers experience a sense of 'ligthening' in timbre as they enter the head register. Head voice can be carried down and maintained lower, into what would naturally be the chest register with little to no risk to the voice, although the tone of the voice will become thinner at lower pitches and resonate more poorly than it would if the natural (chest) voice were being used for those same pitches.

                More detail about training the head voice can be found in Good Tone Production For Singing.

                WHISTLE (OR FLAGEOLET) REGISTER
                The whistle register, (typically occurring between C6 and D7), is the highest register of the human voice, and refers to the register above the head register in female voices. Unlike the other registers within the voice, it does not begin at the same absolute pitch within every female voice type, and there is typically no discernable passaggio marking the transition into this register, which is why it is often considered to be an extension of the head register, rather than a unique or separate register.

                This register has a specific physiological production that is different from that of the other registers, and is so called because the timbre of the notes that are produced from this register are similar to that of a whistle. The quality of sound that is produced is somewhat different from conventional head voice, being excessively bright and edgy. However, this female register is thought to be an extension of head voice, and, ideally, should differ little from head voice in timbre in the well trained voice.

                Women of all voice types can learn to use the whistle register, although lower female voices, such as true contraltos, may not be able to access this register.

                It may be beneficial for female singers to practice flageolet because it encourages a full extension of the vocal folds - at pitches above C6, the folds become their thinnest, with increased damping and diminished mass, offering even more resistance to the exiting air - because it will make high notes within standard repertoire more accessible. In other words, having access to the flageolet register adds freedom to the performable upper range (head register) because it will be easier to execute.

                VOICE CLASSIFICATION
                Through voice classification, singers- voices are evaluated and designated into voice types. Classical terms are used to describe not merely various vocal ranges, but also the specific vocal timbres that are unique to those respective ranges, and that are produced by classical training techniques. (It is difficult to divide popular or non-classical singers into such types because they lack the same classical training.) Voice classification can be somewhat subjective, making it less than a scientific practice.

                Voice classification was developed within classical music, and it is often used within opera to associate possible roles with potential voices. The German Fach system is one popular method of classifying singers, primarily opera singers, by the range, tessitura, vocal weight, and color (timbre) of their voices. The Fach system is a convenience for singers and opera houses. Many opera houses will keep lists of singers divided by their voice classifications and refer to these lists when casting for operas. A singer who is identified as being of a certain Fach will usually be asked to sing only roles that belong to that Fach, which prevents a singer from being asked to sing roles which he or she is incapable of performing, and allows for the best possible casting of roles.

                Choral singers are classified into voice types based mainly on their range. Solo singers are classified into voice types based in part on tessitura - where the voice feels most comfortable and has the most pleasant tone for the majority of the time.

                Many singers are classified incorrectly by unknowlegeable vocal teachers and choir directors. For example, lyric baritones are often miscategorized as tenors because the perceived lightness of their instruments may create a more tenor-like vocal quality and also enable them to sing fairly comfortably in their head registers. Female vocalists who are able to sing high notes are often assumed to be sopranos, regardless of the actual locations of their passaggi, and are often asked to sing soprano parts. Training as another vocal type (e.g., singing too frequently in a tessitura that does not match that of the natural instrument, expecting the voice to reach higher pitches because a singer is thought to be a different or higher type, etc.) can place strain on the voice, not to mention create a great deal of frustration and discouragement and a lack of success in the singer who can't seem to make his or her voice meet certain expectations that are unrealistic due to the mistake of miscategorization. It is, therefore, absolutely critical for instructors and choir directors to understand the importance of the locations of the passaggi (registration pivotal points) in accurately determining voice type, and how vocal weight can affect the perception of what a singer's voice type and range truly are.

                How To Determine Singing Range and Vocal Fach (Voice Type) explains in greater detail why it's important to classify voices and how to do so correctly. It also offers a number of 'notes of interest', as well as observations and discoveries that I have made about range and voice type from my years of teaching.

                TIMBRE
                Timbre simply refers to the quality or 'colour' of tone being produced by the singer.

                For more information about timbre, please read Good Tone Production For Singing.

                VOCAL WEIGHT
                Vocal weight refers to the perceived 'lightness' or 'heaviness' of a singing voice. This quality of the voice is one of the major determining factors in voice classification within classical singing, and constitutes a subcategorization of vocal types (or parts).

                Additionally, vocal weight, which is often determined by the thickness of the vocal folds, may refer to a voice's ability to handle changes in vocal dynamic, and may affect its overall vocal agility, as different voices handle changes in dynamic differently. In other words, vocal weight can affect overall vocal agility and flexibility. For example, heavier voices often have more difficulty maneuvering through florid coloratura passages than lighter voices do. Heavier voices can also sound awkward singing staccato sections because they don't tend to have as much flexibility as lighter voices do. Lighter voices tend to have greater agility and flexibility, but have less facility in filling legato lines, and cannot be heard as well over an orchestra as heavier voices can.

                Lighter voices are often associated with the term 'lyric'. The timbre of these voices is often described as smooth, silky in texture, mellow, sensitive, warm, bright and graceful, and often have a softer, lachcrymous quality. They have good agility - often the ability for coloratura - and strong diction., and can be heard over an orchestra.

                'Coloratura' voices are light with a great deal of high end agility, and are capable of handling florid, elaborately ornamented or embellished vocal passages, including running passages, staccati and trills. Whenever 'coloratura' is used by itself as a voice type, it refers to a soprano with this vocal quality and weight.

                Heavier voices are often associated with the term 'dramatic'. Dramatic voices are very large, strong, powerful, vigorous and rich, and can sing over a full orchestra or choir. The timbre of this type of voice is usually darker and heavier than that of a lyric or coloratura voice, and its tessitura is often a little lower. Because the vocal folds of a singer with this vocal weight are thicker, agility and facility are usually somewhat compromised, however, it is capable of giving dramatic heft to a role, with sustained power.

                Other voice types, like the 'spinto' voice, have a more medium vocal weight. Spintos have a more robust and full sound compared to lyric voices, but are often considered a 'baby dramatic' in that they have larger voices but not quite to the level of dramatic. The spinto voice handles vocal dynamic changes very well. A spinto voice has the brightness and height of a lyric voice, but can be "pushed" to dramatic climaxes without strain, and may have a somewhat darker timbre. It can 'slice' though a full orchestra (rather than 'singing over' it, like a dramatic voice).

                Soubrette is a French voice classification term assigned to women who often play young, flirty physically active operatic roles. In classical music, a soubrette can be considered a female soprano who sings best in middle voice with no strenuous vocal dynamics. Most soubrettes have a warm, bright, sweet vocal colour (timbre), and are comfortable singing throughout the soprano range, although this voice has a lighter vocal weight than that of other soprano voices and a tessitura lying in the mid-range. Their upper extension is not quite as high or 'shiny' as that of a coloratura, but they often have a richer timbre in their middle and upper middle voice.

                For male voices, different terms may be used to described vocal weight. For instance, a Leggiero or light-lyric is the male equivalent of a lyric coloratura. It is a very light, bright, high tenor voice with very natural, high, extensions and a higher tessitura than that of other tenors. Another characteristic of this voice is its flexibility and agility. Lyric or lirico is a strong yet light voice with a high tessitura. A spinto voice is heavier than a lyric, but not quite a dramatic. Drammatico or dramatic tenor is a powerful, rich and full voice with a lower tessitura than a lyric. It, like the female dramatic voice, carries easily over larger orchestras.

                Many voices lie somewhere between different weights (e.g., a lyric coloratura soprano, etc.)

                The weights of certain voice types may be further subcategorized into 'light' and 'full' (e.g., light lyric soprano, full dramatic mezzo-soprano, etc.), which indicates the maturity of sound or tone produced by the singer's voice. Light voices possess a youthful quality and are often ideal for young roles, whereas full voices sound more mature, can be heard (unamplified) over a larger orchestra, and may be able to handle heavier roles.

                TESSITURA
                The term tessitura, (which comes from the Italian word for 'texture'), generally describes the most musically acceptable and comfortable timbre for a given voice type. Put simply, tessitura refers to the range of pitches in which a singer is most comfortable singing, as well as the section of a singer's range where the voice has the most pleasant-sound or tonal quality and easy volume. While a soprano and a mezzo-soprano may have a similar range (as defined by the spectrum of notes that they are both capable of singing), their tessituras will lie in different parts of that range, which is why they are each classified as a different voice type. (To a certain extent, the figures below denoting the expected ranges in repertoire for each voice type reflect tessitura more so than range.)

                Tessitura also refers to the pitch range that most frequently occurs within a given piece, or part, of music. Tessitura addresses not merely a range of pitches but also takes into consideration the arrangement of those pitches in music, or melody (e.g. whether vocal lines and phrases in the musical piece tend to rise gradually or fall quickly, or whether there are large intervals between pitches, as well as the speed of pitch changes), as the abilities of a singer may be more or less suited to certain arrangements of pitch (melodies).

                VOICE TYPE
                Voice type is often confused with vocal range by contemporary or non-classical singers (e.g. those who sing jazz, pop, blues, soul, country, folk and rock styles). For example, if you were to ask some singers what their range is, they may reply by stating that they are a 'tenor' or a 'soprano'. Using the terms range and type interchangeably is inaccurate and can be misleading.

                Perceived qualities or characteristics of a voice help to identify the vocal type. Human singing voices can be described by such qualities as vocal range, weight, tessitura and timbre, as well as vocal registration and vocal transition points that include 'breaks' in the voice, and these qualities describe their vocal types. The designation of a voice as a 'lyric soprano' would be an example of a vocal type.

                In opera, there are six basic voice types - bass, baritone, tenor, contralto/alto, mezzo-soprano and soprano - and then several sub-types within each. However, in North American choral music, there are usually only four vocal types - bass, tenor, alto and soprano - in the arrangements. (When six parts are written into choral arrangements, mezzo-soprano parts are typically called 'second soprano' parts and baritones are often assigned to 'second tenor' parts.)

                There are also intermediate voice types. They may have a range or tessitura lying somewhere between two voice types or parts (e.g., a bass-baritone), or may have a vocal weight lying somewhere between light and heavy (e.g., a dramatic coloratura soprano, etc.). (For more detailed information on how voices are subcategorized by vocal weight, read vocal weight.)

                Below is a list of the basic vocal types and their approximate ranges. I have intended to keep these definitions as simple as possible, without making the complicated distinctions within each vocal type. The ranges listed are based on classical and choral expectations - the 'useful' range - for each voice type rather than on the possible spectrum of notes that singers within each type might be capable of singing. (In other words, these ranges are not static, especially in the case of well-developed singing voices, but represent average ranges in written classical and choral music.)

                For the benefit of more visual readers, I have also included diagrams of a keyboard with the standard (classically and chorally defined) ranges for each vocal type shaded in. The darker shading indicates the range that is assigned to a certain voice type in opera, and the lighter part represents the additional range that might be expected of a singer of the same voice type within choral music. Note how the ranges for each vocal type do a lot of overlapping.

                Finally, I have opted to use scientific pitch notation, where C4 refers to middle C (and A4, the A above middle C, has a frequency of 440Hz), to keep these definitions as succinct as possible. In scientific pitch notation, each octave begins at the note of C, rather than A. (the A immediately below middle C, for example, is A3, and is considered to part of the octave beginning one octave below middle C.) Therefore, the C one octave above middle C is C5, the C one octave below middle C is C3, etc.. (For a better understanding of scientific pitch notation, please read the related section in How To Determine Singing Range and Vocal Fach (Voice Type)

                CONTRABASS
                A bass who can sing G1 or lower is known as a sub-bass or contrabass singer, or a basso profundo. Generally, though, contrabasses are 'lumped in' with other basses when parts are assigned.

                BASS
                A bass singer is considered to be the lowest male part sung in multipart choirs. A typical singing range for a bass singer is F2-E4 with a comfortable range normally between G2 and A3. (A true bass singer is a rarity. In fact, most 'Bass' sections of choirs are comprised of baritones or bass-baritones who have access to lower notes.) The primo passaggio for a bass might be G3, G#4 or A3, while the bass-baritone's is at A3. Their secondo passaggio will be at at C4, C#4 or D4.

                BARITONE
                A baritone refers to the male singer whose range falls somewhere between that of a bass and that of a tenor. A typical range for a baritone is F2-G4 in choral music and G2-E4 in operatic music. A baritone's primo passaggio will lie roughly at Bb3 or B3, and his secondo passaggio at Eb4 or E4, depending on the particular voice's weight.

                BARITENOR
                This intermediate male voice type tends to have the lower extension and 'depth' of timbre of a baritone, yet the lightness, agility and upper extension of a lower tenor. He will switch into middle voice at C4 (his primo passaggio) and into head voice around F4.

                TENOR
                A tenor is considered to be the highest male voice within the modal register. A tenor's typical range in classical repertoire is roughly C3-G4, although the extremes of accessible range can vary greatly from singer to singer. A tenor's primo passaggio will lie roughly at C#4 (drammatico), D4 (lyric), Eb4 (leggiero) or E4 (tenorino), and the second passaggio at around F#4 (heavier tenor voice), G4 (lyric tenor voice) or A4 (leggiero).

                COUNTERTENORS
                Males with high vocal ranges, or who can project falsetto pitches in a clear sound, are referred to as countertenors. Countertenors possess ranges equivalent to those of the female ranges alto, mezzo-soprano and soprano. (A male soprano is specifically referred to as sopranist).

                CONTRALTO
                Contralto is the deepest female singing voice, and the contralto range would be below that of an alto. (Although the subtle distinction between contraltos and altos is typically only made in classical or operatic music, I want to include it here for information purposes.)

                ALTO
                In choral music, alto is the lowest female voice part in a four-part harmony, and the standard range is approximately E3-E5. An alto's first passaggio occurs around Eb4 or E4, and her second passaggio around Eb5 or E5. (Technically, 'alto' is not a voice type, but a designated vocal line in choral music. The range for the alto line in choral music is typically more suitable for mezzo-sopranos, the most common voice type amongst females, than true contraltos.)

                MEZZO-SOPRANO
                Mezzo-soprano refers to a female singer whose range lies between the soprano and the alto/contralto ranges, usually extending from A3-F5. While mezzo-sopranos generally have a slightly heavier, darker tone than sopranos, the mezzo-soprano voice resonates in a higher range (and has a different timbre) than that of an alto voice. A mezzo-soprano's primo passaggio lies around E4 or F4, and her secondo passaggio around E5 or F5.

                SOPRANO
                Sopranos take the highest female part, which usually encompasses the melody of a song, in four-part choral style harmony. Typically, a soprano is expected to be able to sing from C4-A5, or even higher. A soprano's first registration pivotal point (passaggio) lies around F#4 or G4 (although she may feel more comfortable switching out of chest voice and into middle voice lower in the scale), and her second around F#5 or G5.

                SOPRANINO
                Sopranos who can sing higher than C#6 are known as a sopraninos, although they are most likely to be called sopranos. (Of course, there are altos and mezzo-sopranos who are also capable of singing these higher pitches. This is why registration events are more important and accurate in determining Fach than vocal range by itself.)</p>
        </div>
    );
}

export default About;