import React from 'react';

function Contact( props ) {
    return (
        <div className="inner-container">
            <h1>Contact</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dolorum laboriosam soluta ut vitae. Accusantium adipisci aspernatur atque delectus ducimus error eum exercitationem, fugit id labore molestiae nemo nesciunt nobis nulla obcaecati odio odit omnis perferendis placeat provident quasi repellat reprehenderit sed, sit voluptatum. Asperiores dolorum expedita iusto perferendis quia! Aperiam aspernatur autem blanditiis cumque eum ipsum libero perspiciatis? Accusantium assumenda eveniet labore nulla praesentium quae tempore? At commodi cumque dignissimos dolor esse excepturi, facere facilis fuga fugit ipsa labore minus mollitia necessitatibus, nobis odit pariatur perspiciatis placeat porro quam quas quia sequi similique tempora tenetur ut velit vitae voluptas! Consectetur cumque labore laudantium placeat recusandae? Consectetur maiores non recusandae voluptate voluptates? Dolor inventore modi neque similique voluptas. Blanditiis consequatur eveniet minus praesentium quidem repudiandae sequi temporibus unde? Adipisci beatae delectus deleniti distinctio dolor ea esse facere hic in incidunt iure iusto, libero necessitatibus nulla officia quisquam rerum! Animi architecto at aut, commodi consequatur deleniti dolor earum esse ex fuga ipsa nemo nisi nobis odit officia perferendis qui repellat repellendus reprehenderit sint unde vitae voluptas voluptates! Ad blanditiis culpa obcaecati qui rerum? Aspernatur, consequuntur debitis odio recusandae repellat veritatis. Amet asperiores corporis eveniet exercitationem id iure labore laboriosam magnam magni, nisi odio perferendis quod rerum, sunt veritatis, voluptate voluptatibus. Ad corporis dicta dolor itaque quisquam rem! A amet aut consequatur ducimus enim, hic, illum ipsam labore maxime mollitia nobis nostrum perspiciatis porro possimus praesentium quae quisquam quos, repellendus unde vel. Architecto delectus exercitationem nulla perferendis quam quo repudiandae tempora veniam? Adipisci aliquam aliquid, deleniti, nisi non obcaecati pariatur quaerat repellendus reprehenderit sint suscipit totam velit voluptatibus. Ab accusamus illo incidunt obcaecati odio quaerat qui quis saepe suscipit unde. Animi commodi consequuntur, ipsam molestias nobis nostrum placeat quae reprehenderit? Aperiam aut id illo modi nisi. Adipisci at consequatur consequuntur culpa cum debitis deleniti dolor ducimus eaque eius error est explicabo harum id illum ipsam laborum maiores, maxime minima nesciunt nostrum numquam perspiciatis quas quibusdam, quidem quis repellendus repudiandae sit tenetur ullam, unde vitae voluptatibus.</p>
        </div>
    );
}

export default Contact;